version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6003:27017'
    networks:
      - event-platform

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend 
    container_name: catalog_srv
    env_file:
      - ./.env
    ports:
      - "8080:8000"
    networks:
      - event-platform
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend 
    container_name: frontend_app
    ports:
      - "3000:3000"
    networks:
      - event-platform
    volumes:
      - ./frontend:/app
    working_dir: /app # Set the working directory to /app
    command: ["npm", "start"]
    depends_on:
      - backend

networks:
  event-platform:
    driver: bridge

volumes:
  mongo:
