name: Docker CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build frontend image
      run: |
        docker build -f ../../Docker.frontend -t palani1703/catalog-frontend:latest frontend/

    - name: Build backend image
      run: |
        docker build -f ../../Docker.backend -t palani1703/catalog-backend:latest backend/

    - name: Push frontend image
      run: docker push palani1703/catalog-frontend:latest

    - name: Push backend image
      run: docker push palani1703/catalog-backend:latest
